apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crawler-data-saver
  labels:
    app: go-crawler-data-saver
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: go-crawler-data-saver
  template:
    metadata:
      labels:
        app: go-crawler-data-saver
    spec:
      containers:
        - name: go-crawler-data-saver
          image: hataketed/go-crawler-data-saver:0.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1234
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crawler-engine
  labels:
    app: go-crawler-engine
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: go-crawler-engine
  template:
    metadata:
      labels:
        app: go-crawler-engine
    spec:
      containers:
        - name: go-crawler-engine
          image: hataketed/go-crawler-engine:0.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7500
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crawler-portal
  labels:
    app: go-crawler-portal
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: go-crawler-portal
  template:
    metadata:
      labels:
        app: go-crawler-portal
    spec:
      containers:
        - name: go-crawler-portal
          image: hataketed/go-crawler-portal:0.3
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP