apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.host.elastic }}
  labels:
    app: go-crawler-elasticsearch-service
spec:
  type: NodePort
  ports:
    - name: es-client-svc
      port: 9200
      protocol: TCP
      targetPort: esclient
    - name: es-nodes-svc
      port: 9300
      protocol: TCP
      targetPort: esnodes
  selector:
    app: go-crawler-elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.host.dataSaver }}
  labels:
    app: go-crawler-data-saver-service
spec:
  type: NodePort
  ports:
    - name: go-crawler-data-saver-service
      port: 1234
      protocol: TCP
      targetPort: http
  selector:
    app: go-crawler-data-saver
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.host.engine }}
  labels:
    app: go-crawler-engine-service
spec:
  type: NodePort
  ports:
    - name: go-crawler-engine-service
      port: 7500
      protocol: TCP
      targetPort: http
  selector:
    app: go-crawler-engine
---
apiVersion: v1
kind: Service
metadata:
  name: go-crawler-portal
  labels:
    app: go-crawler-portal-service
spec:
  type: NodePort
  ports:
    - name: go-crawler-portal
      port: 8888
      protocol: TCP
      targetPort: http
  selector:
    app: go-crawler-portal