apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-crawler-elasticsearch
  labels:
    app: go-crawler-elasticsearch
spec:
  selector:
    matchLabels:
      app: go-crawler-elasticsearch
  serviceName: "go-crawler-elasticsearch"
  replicas: 1
  minReadySeconds: 3
  template:
    metadata:
      labels:
        app: go-crawler-elasticsearch
    spec:
      containers:
        - name: go-crawler-elasticsearch
          image: library/elasticsearch:7.17.2
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: discovery.type
              value: single-node
            - name: VM_MAX_MAP_COUNT
              value: "262144"
          ports:
            - containerPort: 9200
              name: esclient
            - containerPort: 9300
              name: esnodes